version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.26
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9201:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.26
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5045:5045"
      - "9601:9600"
    command: >
      logstash -e "input { beats { port => 5045 } }
                   output { stdout { codec => rubydebug } }"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.26
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9201
    ports:
      - "5602:5601"

volumes:
  esdata:
    driver: local